Bump Play to version 2.6
guardian/campaign-central pull request #101
Opened 2017-07-26 14:19 UTC by kelvin-chappell

2017-07-26 15:58 UTC, kelvin-chappell commented
![](https://github.trello.services/images/mini-trello-icon.png) [Upgrade Campaign Central to Play 2.6](https://trello.com/c/XTJ7Ecss/123-upgrade-campaign-central-to-play-26)

2017-07-26 16:06 UTC, LATaylor-guardian commented
@kelvin-chappell looks okay to me but I'll default to @philwills given he done this for Riff Raff recently.

2017-07-26 16:15 UTC, philwills requested changes
With the exception of the filters, this looks reasonable.

2017-07-26 16:15 UTC, philwills commented on app/di.scala
> +    super.httpFilters.filterNot(filter => filter == csrfFilter || filter == allowedHostsFilter)
If I'm reading this right, this disables the CSRFFilter. That seems like a bad idea to me unless there's a really compelling reason.

2017-07-27 09:15 UTC, kelvin-chappell commented on app/di.scala
> +    super.httpFilters.filterNot(filter => filter == csrfFilter || filter == allowedHostsFilter)
My thinking is that the app will be no less secure than it is now with these filters disabled, it's clear that they are disabled, and I wanted to make sure that I haven't broken anything before enabling these filters one by one.  The CSRF filter looks like there will be quite a few changes involved.

2017-07-27 09:31 UTC, philwills approved these changes

2017-07-27 09:32 UTC, philwills commented on app/di.scala
> +    super.httpFilters.filterNot(filter => filter == csrfFilter || filter == allowedHostsFilter)
That makes sense, I had thought it was on by default in 2.5.

2017-07-27 10:34 UTC, merged