Campaign list - column's sorting
guardian/campaign-central pull request #56
Opened 2016-11-28 17:34 UTC by Calanthe

This PR introduces column's sorting on the campaign list.

![screen shot 2016-11-28 at 17 33 57](https://cloud.githubusercontent.com/assets/489567/20678983/da257430-b590-11e6-8eaa-b723975faf50.png)

@clloyd @steppenwells

2016-11-29 11:40 UTC, Calanthe commented on public/components/CampaignList/CampaignList.js
> +      'name': 'campaign-list__header-order--desc name',
I know that you prefer to have one css class per tag @clloyd. Do you think that's an issue here?

2016-11-29 11:48 UTC, clloyd requested changes

2016-11-29 11:48 UTC, clloyd commented on public/components/CampaignList/CampaignList.js
> +      'name': 'campaign-list__header-order--desc name',
Does any of this need to be stored in the component state? Can it be implied from the redux global state? Same from the classes, can they be constructed on each render, then you don't need to keep them all in sync?

2016-11-29 11:48 UTC, clloyd commented on public/components/CampaignList/CampaignList.js
> +      this.state.headersCssClasses[value] = 'campaign-list__header-order ' + value;
I don't think you need any of this information in the component state... but even if you do, don't modify this.state directly it won't trigger a render, you should call this.setState

2016-11-29 11:48 UTC, clloyd commented on public/components/CampaignList/CampaignList.js
> +      'name': 'campaign-list__header-order--desc name',
I've no huge issue with two class names where it makes sense, I think it does in this case.

2016-12-01 10:09 UTC, clloyd approved these changes

2016-12-01 10:11 UTC, merged